# Generated by Django 3.0.8 on 2020-07-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='ativo',
            new_name='aprovado',
        ),
    ]
