# Generated by Django 3.0.8 on 2020-07-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200704_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='email',
            field=models.EmailField(help_text='Obrigatório', max_length=254),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='mensagem',
            field=models.TextField(help_text='Máximo 500 caracteres', max_length=500),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nome',
            field=models.CharField(help_text='Obrigatório', max_length=80),
        ),
    ]
